version: '3.9'

services:
  db:
    container_name: wti_db
    image: 'postgres:15-alpine'
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_DB=${DATABASE_NAME}
    ports:
      - '127.0.0.1:${DATABASE_PORT}:5432'
    volumes:
      - ./DockerVolumes/PostgresDb:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 5s
      timeout: 10s
      retries: 3
      start_period: 3s
      
  amqp:
    container_name: wti_amqp
    image: 'rabbitmq:3.12-management-alpine'
    restart: unless-stopped
    ports:
      - '${AMQP_PORT}:5672'
      - '${AMQP_MANAGEMENT_PORT}:15672'
    environment:
      - RABBITMQ_DEFAULT_USER=${AMQP_USERNAME}
      - RABBITMQ_DEFAULT_PASS=${AMQP_PASSWORD}
    volumes:
      - ./DockerVolumes/RabbitMq/data/:/var/lib/rabbitmq/
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 10s
      retries: 3